language: node_js
node_js:
  - "node"
  - "10"
cache:
  directories:
    - node_modules
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm test -- --coverage # Include coverage when running tests
  - npm run build
after_script: # Upload coverage reports
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls
  - CC_TEST_REPORTER_ID=$cc_test_reporter_id ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
